version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ourglass
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ourglassdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
