version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ourglass
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ourglassdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  api:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "npm install --silent && npx prisma migrate deploy && npm start"
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install --silent && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - api

  worker:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: sh -c "npm install --silent && node auctionWorker.js"
    env_file:
      - .env
    depends_on:
      - db
